site_name: cninfo-python-sdk
site_description: An SDK library for cninfo.com
site_author: thomaszdxsn

repo_url: https://github.com/thomaszdxsn/cninfo-python-sdk
edit_uri: https://github.com/thomaszdxsn/cninfo-python-sdk/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
